### ISSUE TITLE
error during gigalixir signup or login

### ISSUE THREAD

**Issue by nunziofiore** [gigalixir/gigalixir-getting-started#7]
Hi,
 perhaps is a python error in my configuration but I can't find nothing on internet to solve, so I wish that someone from gigalixir can help me.
The scene is this:

`➜  ~ sudo pip3 install gigalixir --ignore-installed six
The directory '/Users/nunziofiore/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/nunziofiore/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.

Collecting gigalixir
Collecting six
  Downloading six-1.11.0-py2.py3-none-any.whl
Collecting requests~=2.13.0 (from gigalixir)
  Downloading requests-2.13.0-py2.py3-none-any.whl (584kB)
    100% |████████████████████████████████| 593kB 2.2MB/s

Collecting click~=6.7 (from gigalixir)
  Downloading click-6.7-py2.py3-none-any.whl (71kB)
    100% |████████████████████████████████| 71kB 1.0MB/s

Collecting rollbar~=0.13.11 (from gigalixir)
Collecting stripe~=1.51.0 (from gigalixir)
  Downloading stripe-1.51.0-py3-none-any.whl (203kB)
    100% |████████████████████████████████| 204kB 862kB/s

Installing collected packages: requests, click, six, rollbar, stripe, gigalixir

Successfully installed click-6.7 gigalixir-0.19.0 requests-2.13.0 rollbar-0.13.17 six-1.11.0 stripe-1.51.0

➜  ~ gigalixir signup

Traceback (most recent call last):
  File "/usr/local/bin/gigalixir", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1063, in invoke
    Command.invoke(self, ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/gigalixir/__init__.py", line 76, in cli
    raise Exception("Unknown platform: %s" % PLATFORM)
Exception: Unknown platform: b'darwin'`

Can you help me?
Nunzio

**Comment by jesseshieh** [comment]
Unfortunately, we don't support Python 3 yet. Try using Python 2 (pip2) instead.

**Comment by nunziofiore** [comment]
I'll try

**Comment by jesseshieh** [comment]
We made some changes and Python 3 should work now for most commands but it still isn't officially supported. Closing for now, but feel free to reopen.
