### ISSUE TITLE
npm ERR! Could not install from "../../deps/phoenix" as it does not contain a package.json file.

### ISSUE THREAD

**Issue by drernie** [gigalixir/gigalixir-getting-started#8]
While following the README, I get an error during the `npm install`:
```
npm ERR! code ENOLOCAL
npm ERR! Could not install from "../../deps/phoenix" as it does not contain a package.json file.
```
[2018-02-06T11_07_16_511Z-debug.log](https://github.com/gigalixir/gigalixir-getting-started/files/1698742/2018-02-06T11_07_16_511Z-debug.log)

When I run Phoenix, I get a warning about the assets, and no JS or CSS files are loaded.

**Comment by drernie** [comment]
cf. https://stackoverflow.com/questions/44677848/npm-install-npm-cant-find-a-package-json-file-in-current-directory

**Comment by jesseshieh** [comment]
Was this an existing app? If so, did it work before you started following the readme?

**Comment by drernie** [comment]
$ node -v
v9.5.0
$ npm -v
5.6.0

**Comment by drernie** [comment]
No, this was a clean install from this repo (via zip file).

**Comment by drernie** [comment]
$ uname -a
Darwin newkapi.local 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64

**Comment by drernie** [comment]
FWIW, I get the same error when running brunch:
```
$ brunch -v
2.10.9
$ brunch build
03:29:51 - info: Using outdated versions of phoenix, phoenix_html, trying to update to match package.json versions
03:29:52 - info: Installing packages with npm...
03:29:54 - error: Command failed: npm install 
npm ERR! code ENOLOCAL
npm ERR! Could not install from "../deps/phoenix" as it does not contain a package.json file.
```

**Comment by drernie** [comment]
I re-downloaded and ran and it looks good.  Must've been a config issues on my side. Thanks!

**Comment by gondwe** [comment]
Not following @drernie what did you redownload im having the same issue trying to use heroku belt on remote repo.

**Comment by juliusdejon** [comment]
Declare it as current directory path, change your phoenix file dependecy from `phoenix: "file:/deps/phoenix"` to  `phoenix: "file:./deps/phoenix"` and also   "phoenix_html": "file:./deps/phoenix_html"

**Comment by streamerd** [comment]
if that is a new phoenix app, make sure  to run:

`$ mix deps.get 
`
before issuing an: 

`$ cd assets && npm install && node node_modules/brunch/bin/brunch build
`
